### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by merlinaudio** [Swift-Watch/swift-watch#16]
Hi! I'm new to Swift

This is an awesome tool, but I had troubles figuring out how to make it work.

Maybe we could change the install instructions? e.g.

---

# Installation

```sh
git clone https://github.com/Swift-Watch/swift-watch.git
cd ./swift-watch
swift build -c release
```

Then add `.build/release/swift-watch` to your `PATH`. For example by linking it in /usr/local/bin

```sh
sudo ln -s $(realpath ./.build/release/swift-watch) /usr/local/bin
```

---

Also, there is no executable product, so it doesn't work with `mint`. If it's not too hard, I could attempt a PR to add this.

Thanks for your work on this tool, it really helps a lot :) Swift is becoming more popular outside of the apple ecosystem (and xcode) so without swift-watch, having to `switch run` every time would become tiring fast

**Comment by regexident** [comment]
Hi @merlindru, sorry for the late response.

I've improved the README's [Installation section](https://github.com/regexident/swift-watch#installation).

> Also, there is no executable product, so it doesn't work with `mint`. If it's not too hard, I could attempt a PR to add this.

I've added an executable product to the `Package.swift` file.

> Thanks for your work on this tool, it really helps a lot :)

Happy to hear you find it useful!
