### ISSUE TITLE
Ignore file changes while running?

### ISSUE THREAD

**Issue by subdigital** [Swift-Watch/swift-watch#17]
I have a test that writes to an actual file, when I run this test, swift-watch picks up the change and runs again, repeatedly.

Is there a way to ignore certain files, or a mode that would ignore changes _while_ running a task, so we can workaround this type of scenario?

Thanks! Glad to see this tool in the Swift ecosystem ❤️

**Comment by regexident** [comment]
Watch/ignore patters (based on [glob()](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/glob.3.html)) are the two remaining items on the project's [roadmap](https://github.com/regexident/swift-watch#roadmap).

I just pushed a somewhat crude implementation of "ignore file changes while running tasks".
Lemme know if it addresses your issue. 🤞

**Comment by subdigital** [comment]
Works perfectly! Thank you! ❤️

**Comment by subdigital** [comment]
I just noticed that it's leaving a `dummy.txt` in the working dir. I assume that was just a test to prove that it works?

**Comment by regexident** [comment]
Oh, you're right! Fixed. 🫣
